FROM java:8-jre
MAINTAINER Abhishek kumar <ashuindia96@gmail.com>
COPY ./target/neo4jmodelling-service-1.0.0-SNAPSHOT.jar /usr/src/neo4jmodelling-service-1.0.0-SNAPSHOT.jar
WORKDIR /usr/src
ENTRYPOINT ["java","-jar", "neo4jmodelling-service-1.0.0.jar"]



