FROM java:8-jre
MAINTAINER  Sashi Kumar Singh <sashi18singh@gmail.com>
COPY ./target/userprofileservice-1.0.0.jar /usr/app/src/userprofileservice-1.0.0.jar
WORKDIR /usr/app/src
ENTRYPOINT ["java","-jar", "userprofileservice-1.0.0.jar"]
